<?php
$title = 'Choose a new password';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title); ?></h1>

<?php
/* @var $form Zend\Form\FormInterface */
$form = $this->form;
$id = $this->id;
$form->setAttribute('action', $this->url('flaminguser/change-password', array(), array(
	'query' => array(
		'id' => $id
	)
)));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('password'));

echo $this->formRow($form->get('passwordVerify'));

echo $this->formHidden($form->get('csrf'));
?>

<div class="form-actions">
	<?= $this->formSubmit($form->get('submit')); ?>
</div>

<?php
echo $this->form()->closeTag();