<?php
$title = 'Forgot your password?';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title); ?></h1>

<p>Write your email here. We'll send you a link where you can choose a new password.</p>

<?php
/* @var $form Zend\Form\FormInterface */
$form = $this->form;
$form->setAttribute('action', $this->url('flaminguser/forgot-password'));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('email'));

echo $this->formHidden($form->get('csrf'));
 ?>

<div class="form-actions">
	<?= $this->formSubmit($form->get('submit')); ?>
</div>

<?php
echo $this->form()->closeTag();